/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "<aws-region>",
    "aws_cognito_identity_pool_id": "<aws_cognito_identity_pool_id>",
    "aws_cognito_region": "<aws-cognito-region>",
    "aws_user_pools_id": "<aws_user_pools_id>",
    "aws_user_pools_web_client_id": "<aws_user_pools_web_client_id>",
    "oauth": {
        "domain": "<domain>.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://localhost:3000/",
        "redirectSignOut": "https://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://<url-prefix>.appsync-api.<region>.amazonaws.com/graphql",
    "aws_appsync_region": "<region>",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "<api_key>"
};


export default awsmobile;